### ISSUE TITLE
How to calculate flops

### ISSUE THREAD

**Issue by stnjumu** [IDEA-Research/DAB-DETR#51]
Hi! thanks for your excellent work, I'm wondering how to evaluate the flops of DAB-DETR model?
I can't directly use the DETR script which will get AssertionError in jit_handles.py.
https://github.com/facebookresearch/detr/issues/110
Could you pls share your python script?

**Comment by SlongLiu** [comment]
We provide a file for flops in DINO https://github.com/IDEA-Research/DINO/tree/main/tools. Hope it is helpful.

**Comment by stnjumu** [comment]
Thanks for your excellent work, this is very helpful.
